# OUTPUT          =
# OUTLIB          =
# SOURCES         =
# INCLUDE_DIRS    =
# LIB_DIRS        =
# CC              =
# CXX             =
# LD              =
# AR              =
# OBJCOPY         =
# CFLAGS          = 
# CXXFLAGS        = 
# LIBS            =
# LDFLAGS         = 
# ADDITIONAL_DEPS = 
# COVFLAGS		  =

include ultimate-makefile/Makefile.ultimate
