BUILTIN_FLAGS += -DTESTCOMPILE
BUILTIN_FLAGS += -fmax-errors=5
BUILTIN_FLAGS += -g3
BUILTIN_FLAGS += -rdynamic
BUILTIN_FLAGS += -ftest-coverage
BUILTIN_FLAGS += -fprofile-arcs
BUILTIN_FLAGS += --coverage
BUILTIN_FLAGS += -fno-exceptions
BUILTIN_FLAGS += -fdelete-null-pointer-checks
BUILTIN_FLAGS += -fno-inline

CXXFLAGS += $(BUILTIN_FLAGS) $(TEST_FLAGS)
CFLAGS += $(BUILTIN_FLAGS) $(TEST_FLAGS)

OUTPUT = $(TEST_BINARY_NAME)
SOURCES = TestMain.cpp $(TEST_SOURCES)
INCLUDE_DIRS = $(TEST_INCLUDE_DIRS)
LIBS = CppUTest CppUTestExt $(TEST_LIBS)

LD = $(CXX)

include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/Makefile.ultimate

CLEAN_EXTRA += coverage *.gcda *.gcno $(ADDITIONAL_BINARIES)

LCOVDIR = coverage
LCOVFILE = $(LCOVDIR)/coverage.info
LCOVFLAGS = -q --no-recursion --rc lcov_branch_coverage=1 -o $(LCOVFILE)

test: $(TEST_BINARY_NAME)
	@mkdir -p coverage
	@lcov -q --zerocounters --directory ..
	./$(TEST_BINARY_NAME) $(CPPUTEST_FLAGS)
	@lcov $(LCOVFLAGS) -c -d $(OBJDIR)/$(CURDIR)
	@lcov -r $(LCOVFILE) "/usr*" $(LCOVFLAGS)
	@genhtml --rc lcov_branch_coverage=1 -q --highlight --demangle-cpp $(LCOVFILE) --output-directory coverage
	
